### ISSUE TITLE
external files

### ISSUE THREAD

**Issue by beilinli** [bli0042/cellblender-plot#1]
Moving external files (Highcharts, JQuery, etc.) offline results in slow or failed loading.
- get Highcharts/JQuery offline
- not so sure about the others, esp. exporting.js which requires an external server (?)

**Comment by bli0042** [comment]
Tabs
- bugs fixed
- implement series removal (tab removal exists)
- avoid duplicate series
- scroll tabs when there are too many

**Comment by bli0042** [comment]
JQuery UI
- move offline (something went wrong after downloading)
- finish resizable/draggable elements (for now, everything)

**Comment by bli0042** [comment]
* Pages not loading seems to be a Safari-specific problem.
* The more files hosted locally, more likely to not load (mostly when reloading the page in browser).
* Firefox/Chrome work better, but slower loading as number of local files increases.

**Comment by beilinli** [comment]
Minifying the concatenation of all the library JS files works; not sure if this is "best practice."

http://jscompress.com
- external/jquery.min.js (JQuery 1.10.2)
- external/highcharts.js
- external/jquery-ui-1.11.4.custom/jquery-ui.min.js (JQuery UI 1.11.4)
- external/customEvents.js
- external/exporting.js
- external/spectrum.js
- ~~external/common-display.js (8-14-2015)~~
  (first 2 must be first)

CSS
- external/spectrum.css
- external/jquery-ui-1.11.4.custom/jquery-ui.min.css

**Comment by bli0042** [comment]
Left separate files for now

Last commits with all-min.js: 8340931, c6d673c
Last commits with online files: d3059b9, d844203, 23dfed2

**Comment by beilinli** [comment]
Separate files are still (mostly) fine for plot-main.js, but causing problems with histogram (just added another file for functions shared between both pages to avoid duplication).

Actually it seems it is fairly common to combine all the external files (if they are local). See http://stackoverflow.com/questions/9500052/is-it-usual-practice-to-combine-and-minify-external-js-libraries-and-css-files. There would only be a need for the library files though.

**Comment by beilinli** [comment]
current: all-min.js and all-min.css (common-display.js separate)
3382159: all-min.js (includes common-display.js, mistake) only

[without common-display.js]
955ee44: all separate in plot-main.html

To get header with all separate files, see 955ee44
