### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by beilinli** [bli0042/cellblender-plot#12]
Add unit tests.
- current simulation (a-d world)
- large file
- many files
- more (TBD)

**Comment by bli0042** [comment]
- getting 10^5 files (or 10^5-length files) uploaded
- test

**Comment by beilinli** [comment]
- getting many files uploaded
- getting very long files uploaded

notes
- adding series triggers set extremes
- adding lots of options to JS select is okay (so work on not loading series until needed)
